version: '3.8'

services:
  backend1:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend1:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=3000
      - REACT_APP_BACKEND_PORT=3001
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend2:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=4001
    ports:
      - 4001:4001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend2:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=4000
      - REACT_APP_BACKEND_PORT=4001
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend3:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=5001
    ports:
      - 5001:5001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend3:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=5000
      - REACT_APP_BACKEND_PORT=5001
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./frontend:/app
