version: '3.8'

services:
  # bootstrap1:
  #   build:
  #     dockerfile: Dockerfile
  #     context: "./bootstrap"
  #   environment:
  #     - PORT=6001
  #     - KEY_FILE=b_1.json
  #   ports:
  #     - 6001:6001
  #   volumes:
  #     - /app/node_modules
  #     - ./bootstrap:/app

  # bootstrap2:
  #   build:
  #     dockerfile: Dockerfile
  #     context: "./bootstrap"
  #   environment:
  #     - PORT=7001
  #     - KEY_FILE=b_2.json
  #   ports:
  #     - 7001:7001
  #   volumes:
  #     - /app/node_modules
  #     - ./bootstrap:/app
  
  # bootstrap3:
  #   build:
  #     dockerfile: Dockerfile
  #     context: "./bootstrap"
  #   environment:
  #     - PORT=8001
  #     - KEY_FILE=b_3.json
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - /app/node_modules
  #     - ./bootstrap:/app

  backend1:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend1:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=3000
      - REACT_APP_BACKEND_PORT=3001
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend2:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=4001
    ports:
      - 4001:4001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend2:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=4000
      - REACT_APP_BACKEND_PORT=4001
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend3:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=5001
    ports:
      - 5001:5001
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend3:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=5000
      - REACT_APP_BACKEND_PORT=5001
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./frontend:/app
