version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    environment:
      - PORT=${REACT_APP_BACKEND_PORT}
      - BOOTSTRAP_IP=${BOOTSTRAP_IP}
      - ITEMS_PER_USER=${ITEMS_PER_USER}
      - EXPIRATION_TIME=${EXPIRATION_TIME}
    ports:
      - ${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=${REACT_APP_FRONTEND_PORT}
      - REACT_APP_BACKEND_PORT=${REACT_APP_BACKEND_PORT}
    ports:
      - ${REACT_APP_FRONTEND_PORT}:${REACT_APP_FRONTEND_PORT}
    volumes:
      - /app/node_modules
      - ./frontend:/app
